# https://circleci.com/docs/2.0

version: 2
jobs:

  build_sender:
    working_directory: ~/aws.notifier/src/sender
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout:
          path: ~/aws.notifier
      - restore_cache:
          keys:
          - sender-modules-{{ checksum "package.json" }}
          - sender-modules-
      - run:
          name: Install modules
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          key: sender-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Zipping for Lambda deployment
          command:
            zip -r sender-${CIRCLE_BRANCH}.zip *
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install python-dev
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli --upgrade
      - deploy:
          name: Upload artifact to S3
          command: |
            aws s3 sync . s3://vvc.aws.notifier.ops --exclude "*" --include "sender-${CIRCLE_BRANCH}.zip"

  deploy_infra:
      docker:
        - image: circleci/node:8.10
      working_directory: ~/aws.notifier/
      steps:
        - checkout
        - run:
            name: Install Terraform
            command: |
              sudo wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
              sudo unzip terraform.zip -d /usr/local/bin
        - run:
            name: Install AWS CLI
            command: |
              sudo apt-get install python-dev
              sudo curl -O https://bootstrap.pypa.io/get-pip.py
              sudo python get-pip.py
              sudo pip install awscli --upgrade
        - run:
            name: Get all artifacts from S3
            command: |
                aws s3 sync s3://vvc.aws.notifier.ops ./terraform --exclude "*" --include "*-${CIRCLE_BRANCH}.zip"
        - deploy:
            name: Terraform INIT, PLAN and APPLY or DESTROY
            working_directory: ~/aws.notifier/terraform
            command: |
              terraform init -var-file=vars/${CIRCLE_BRANCH}.tfvars -input=false
              if (terraform workspace list | grep ${CIRCLE_BRANCH}); then terraform workspace select ${CIRCLE_BRANCH}; else terraform workspace new ${CIRCLE_BRANCH}; fi
              terraform plan -var-file=vars/${CIRCLE_BRANCH}.tfvars -input=false
              terraform apply -var-file=vars/${CIRCLE_BRANCH}.tfvars -auto-approve
              export APIENDPOINT=$(terraform show -no-color | grep 'api-sender-endpoint' | awk '{print $3}')
              curl -X POST --data-urlencode "payload={\"channel\": \"#aws_notifier_pipeline\", \"username\": \"confirmer:\", \"text\": \" Evironment: $CIRCLE_BRANCH \n API: $APIENDPOINT \", \"icon_emoji\": \":thumbsup:\"}" https://hooks.slack.com/services/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

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build_sender
      - deploy_infra:
          requires:
            - build_sender
